{
 "title": "Flink state analysis",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Busyness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=\"TumblingEventTimeWindows____DummyLatencySink\"}"
    }
   ]
  },
  {
   "title": "Map busy time and split backpressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "TaskManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "TM replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(flink_taskmanager_Status_JVM_CPU_Time)"
    }
   ]
  },
  {
   "title": "Stateful operator parallelism",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(flink_taskmanager_job_task_numBytesOut{task_name=\"TumblingEventTimeWindows\"})"
    },
    {
     "expr": "count(flink_taskmanager_job_task_numBytesOut{task_name=\"TumblingEventTimeWindows____DummyLatencySink\"})"
    }
   ]
  },
  {
   "title": "Num records out per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "expr": "sum by(job_id)(flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TumblingEventTimeWindows\"})"
    },
    {
     "expr": "sum by(job_id)(flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TumblingEventTimeWindows____DummyLatencySink\"})"
    }
   ]
  },
  { "title": "RocksDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "RocksDB cache hit + miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_hit"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_miss"
    }
   ]
  },
  {
   "title": "RocksDB cache hit percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m]) / (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m]) + rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[1m])))"
    }
   ]
  },
  {
   "title": "RocksDB bytes read + written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_bytes_read"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_bytes_written"
    }
   ]
  },
  {
   "title": "RocksDB block cache usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_usage"
    }
   ]
  },
  {
   "title": "Live SST files size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_column_family_rocksdb_live_sst_files_size"
    }
   ]
  },
  {
   "title": "Estimate table readers mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_table_readers_mem"
    }
   ]
  },
  {
   "title": "State GET latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_state_name_valueStateGetLatency / 1000000"
    }
   ]
  },
  {
   "title": "State UPDATE latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency / 1000000"
    }
   ]
  },
  {
   "title": "Estimate num keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_num_keys"
    }
   ]
  }
 ]
}