################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: flink-query1
spec:
  deploymentName: flink
  flinkConfiguration:
    job.autoscaler.enabled: "true"
    job.autoscaler.stabilization.interval: "1m"
    #job.autoscaler.memory.tuning.enabled: "true"
    job.autoscaler.metrics.window: "2m"
    pipeline.max-parallelism: "24"
    taskmanager.numberOfTaskSlots: "4"
    execution.checkpointing.interval: "1m"
    jobmanager.scheduler: adaptive
    job.autoscaler.target.utilization: "0.5"
    job.autoscaler.target.utilization.boundary: "0.3"
    metrics.reporters: prom
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    #metrics.reporter.prom.port: 9250-9260
    web.submit.enable: "true"
    web.cancel.enable: "true"
    state.backend: "rocksdb"
    s3.endpoint: "http://minio.manager:9000"
    s3.path.style.access: "true"
    s3.access-key: "root"
    s3.secret-key: "rootroot"
    state.savepoints.dir: s3://flink/flink-checkpoints
    state.checkpoints.dir: s3://flink/flink-checkpoints
  job:
    jarURI: https://forge.uclouvain.be/DonatienSchmitz/justin/-/raw/33e0f192cbc25f0afb604dcc029495526c93307d/nexmark/Query8.jar
    parallelism: 1
    upgradeMode: stateless
    args:
      - "--auction-srcRate"
      - "60000"
      - "--person-srcRate"
      - "30000"
      - "--fixedRate"
      - "true"
      - "--changingRateInterval"
      - "180000"
      - "--changingRateRatio"
      - "0.65"
      - "--changingRateSteps"
      - "2"

---

apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: flink-query2
spec:
  deploymentName: flink
  flinkConfiguration:
    job.autoscaler.enabled: "true"
    job.autoscaler.stabilization.interval: "1m"
    #job.autoscaler.memory.tuning.enabled: "true"
    job.autoscaler.metrics.window: "2m"
    pipeline.max-parallelism: "24"
    taskmanager.numberOfTaskSlots: "4"
    execution.checkpointing.interval: "1m"
    jobmanager.scheduler: adaptive
    job.autoscaler.target.utilization: "0.5"
    job.autoscaler.target.utilization.boundary: "0.3"
    metrics.reporters: prom
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    #metrics.reporter.prom.port: 9250-9260
    web.submit.enable: "true"
    web.cancel.enable: "true"
    state.backend: "rocksdb"
    s3.endpoint: "http://minio.manager:9000"
    s3.path.style.access: "true"
    s3.access-key: "root"
    s3.secret-key: "rootroot"
    state.savepoints.dir: s3://flink/flink-checkpoints
    state.checkpoints.dir: s3://flink/flink-checkpoints
  job:
    jarURI: https://forge.uclouvain.be/DonatienSchmitz/justin/-/raw/33e0f192cbc25f0afb604dcc029495526c93307d/nexmark/Query8.jar
    parallelism: 1
    upgradeMode: stateless
    args:
      - "--auction-srcRate"
      - "20000"
      - "--person-srcRate"
      - "15000"
      - "--fixedRate"
      - "true"
      - "--changingRateInterval"
      - "180000"
      - "--changingRateRatio"
      - "0.65"
      - "--changingRateSteps"
      - "2"