defaultConfiguration:
  create: true
  append: true
  justin.enabled: true
  flink-conf.yaml: |+
    kubernetes.operator.metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    kubernetes.operator.metrics.reporter.prom.port: 9999
  log4j-operator.properties: |+
    # Flink Operator Logging Overrides
    rootLogger.level = DEBUG
  log4j-console.properties: |+
    # Flink Deployment Logging Overrides
    rootLogger.level = DEBUG  
